package section1;

public class TryCatchTest {

	public static void main(String[] args) {
		int arr[] = {1,2,3};
		// arr[0] ~ arr[2]
		try {
			System.out.println(arr[3]); // 예외가 발생되는 코드
		} catch (ArrayIndexOutOfBoundsException e) {
			   //                           int a
			
			   //                        Coffee c = new Coffee();
		}
	}
}
